"""
25_bundle_examples_numbered.py
------------------------------
Supplementary material for Figure 2. Reuses the bundle panel of
scripts/24_bundle_examples.py to draw the identical figure with a fine
number beside each task point, and writes the table that the numbers key
into. The paper carries the plain panel (24); the supplement carries this
numbered panel and its table, so a reader can trace any point to its task.

The numbering is per occupation, running from one around the disk in order
of angle. Colours, markers, centroids and the chi/xi/r_o marks are exactly
those of 24; only the numbers and the table are added here. Nothing is
hardcoded: the figure and the table are both functions of the frozen data,
and the occupation set is whatever SELECTED holds in 24.

Output:
    results/bundle_examples_numbered.png    the numbered panel
    results/bundle_examples_tasks.tex       longtable, grouped by occupation
    results/bundle_examples_tasks.csv       the same rows, for the record

The .tex needs \\usepackage{longtable} and \\usepackage{booktabs}.

Usage:
    python scripts/25_bundle_examples_numbered.py
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

REPO_ROOT = Path(__file__).resolve().parents[1]
RESULTS = REPO_ROOT / "results"


def load_producer():
    """Import scripts/24_bundle_examples.py (its name starts with a digit,
    so it is loaded by path rather than by a plain import)."""
    path = Path(__file__).with_name("24_bundle_examples.py")
    spec = importlib.util.spec_from_file_location("bundle_examples", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_LATEX = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
          "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
          "^": r"\textasciicircum{}", "\\": r"\textbackslash{}"}


def latex_escape(s: str) -> str:
    return "".join(_LATEX.get(c, c) for c in str(s))


def write_table(bundles) -> None:
    rows = []            # for the csv
    lines = [
        r"% Auto-generated by scripts/25_bundle_examples_numbered.py.",
        r"% Needs \usepackage{longtable} and \usepackage{booktabs}.",
        r"\begin{longtable}{@{}r p{0.72\textwidth} l@{}}",
        r"\caption{Tasks of the example occupations of Figure~\ref{fig:geometry-map}, "
        r"keyed to the numbers in the supplementary numbered panel. Direction is the "
        r"compass sector of the task on the disk.}"
        r"\label{tab:bundle-tasks}\\",
        r"\toprule",
        r"No. & Task & Direction \\ \midrule",
        r"\endfirsthead",
        r"\multicolumn{3}{c}{\tablename\ \thetable\ (continued)}\\",
        r"\toprule No. & Task & Direction \\ \midrule",
        r"\endhead",
        r"\midrule \multicolumn{3}{r}{continued on next page}\\",
        r"\endfoot",
        r"\bottomrule",
        r"\endlastfoot",
    ]
    for k, b in enumerate(bundles):
        title = latex_escape(b["title"])
        if k > 0:
            lines.append(r"\addlinespace")
        lines.append(rf"\multicolumn{{3}}{{@{{}}l@{{}}}}{{\textit{{{title}}}}}\\")
        lines.append(r"\addlinespace[2pt]")
        for _, r in b["tasks"].iterrows():
            num = int(r["num"])
            task = latex_escape(r["Task"])
            direction = r["dir"]
            lines.append(rf"{num} & {task} & {direction} \\")
            rows.append((b["title"], b["onet_code"], num, direction,
                         round(float(r["deg"]), 1), round(float(r["chi"]), 3),
                         str(r["Task"])))
    lines.append(r"\end{longtable}")
    (RESULTS / "bundle_examples_tasks.tex").write_text("\n".join(lines) + "\n")

    import csv
    with open(RESULTS / "bundle_examples_tasks.csv", "w", newline="") as fh:
        wr = csv.writer(fh)
        wr.writerow(["occupation", "onet_code", "number", "direction",
                     "deg", "chi", "task"])
        wr.writerows(rows)


def main() -> None:
    mod = load_producer()
    fig, bundles = mod.build_panel(numbered=True)
    fig.savefig(RESULTS / "bundle_examples_numbered.png", dpi=200)
    plt.close(fig)

    write_table(bundles)

    total = sum(b["n"] for b in bundles)
    for b in bundles:
        print(f"  {b['title'][:34]:34s} tasks 1..{b['n']}")
    print(f"  {total} tasks over {len(bundles)} occupations")
    print(f"wrote {RESULTS/'bundle_examples_numbered.png'}")
    print(f"wrote {RESULTS/'bundle_examples_tasks.tex'}")
    print(f"wrote {RESULTS/'bundle_examples_tasks.csv'}")


if __name__ == "__main__":
    main()
